### ISSUE TITLE
Vaadain productionMode prevent Viritin js download

### ISSUE THREAD

**Issue by gokhanoner** [viritin/vwscdn#4]
When you set the below parameter on application properteis,  I'm getting error in the image?

```
vaadin.servlet.productionMode=true
```

![image](https://cloud.githubusercontent.com/assets/6715308/9719358/2ed69ba0-558c-11e5-8a01-6319e4ec5a77.png)

For prod, should I take this js and copy it to local ? Actually, I need to because my appl. will run internally, server doesn't have internet access..

**Comment by mstahv** [comment]
@samie Do you have any idea what could cause this?

@gokhanoner, the server don't need internet access, but the clients accessing it do (and the machine that builds the project) do need. If also clients cannot access internet, you could try adding this configuration to your plugin settings:

```
            <configuration>
                <vwscdn.download>true</vwscdn.download>
            </configuration>
```

That should download the widgetset to the local war file, and serve it from there. vwscdn would then be needed only for "cloud compilation" of widgetset, but serving locally. Not sure though if it works with Spring Boot which you are using(?).

**Comment by gokhanoner** [comment]
Yes, I'm using spring boot. I actually see this error while testing your crud example. Added that 1 line to application.properties file and while loading the main screen, I got that error. Really weird.

**Comment by gokhanoner** [comment]
By the way, config option didn't help, it didn't download the widgetset and still same error.

**Comment by gokhanoner** [comment]
```
@Parameter(property = "vwscdn.download", defaultValue = "false", readonly = true)
private boolean download;
```

that parameter is read-only. I think this is way I cannot change it.

**Comment by gokhanoner** [comment]
Are there any update on this ?

**Comment by gokhanoner** [comment]
How can I use this in my project. Is 1.3.6-SNAPSHOT available in maven ?

**Comment by mstahv** [comment]
Just built a release. For me 1.3.5 just appeared in maven central. Might take a while for all servers to update. I'll update the site to advertise 1.3.5 in a minute.

**Comment by gokhanoner** [comment]
Perfect, now I can see.

should I open another one for vwscdn.download option to be enabled?

**Comment by mstahv** [comment]
I think the download option should work, I have used it myself. I can look at it at some point, but feel free to add an issue to add documentation for it (almost useless feature currently).
