### ISSUE TITLE
vwscdn.download parameter is readonly

### ISSUE THREAD

**Issue by gokhanoner** [viritin/vwscdn#5]
```
@Parameter(property = "vwscdn.download", defaultValue = "false", readonly = true)
private boolean download;
```

Because of this parameter is defined read-only, user cannot set it to true, therefore cannot download the file to local.

Removing `readonly = true` will solve the issue.

**Comment by gokhanoner** [comment]
Any update on this one ? Waiting this to complete tests & release the appl. to production.

**Comment by mstahv** [comment]
Hi, the configuration parameter is "download" I just tried and with this configuration:

```
            <plugin>
            <groupId>in.virit.vwscdn</groupId>
            <artifactId>vwscdn-maven-plugin</artifactId>
            <version>1.3.5</version>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <download>true</download>
            </configuration>
        </plugin>
```

**Comment by mstahv** [comment]
I don't know how this readonly affects, but this feature should at least be documented on the site as an option for deployment.

**Comment by gokhanoner** [comment]
Yep, I confirm that download property is working.

One more thing, I don't know if it's an issue or my misusage:

I set also this:

```
<downloadedDirectory>${project.basedir}/src/main/resources/VAADIN/widgetset</downloadedDirectory>
```

But code looks for `/VAADIN/widgetsets` folder ?? Is that name is fixed so I should also use it as widgetsets or is it a bug ? (It's not critical, just trying to confirm.)
