### ISSUE TITLE
vaadin 7.6 compile issue

### ISSUE THREAD

**Issue by gokhanoner** [viritin/vwscdn#6]
I'm gettin empty in.virit package. Using 7.6-SNAPSHOT & 1.3.6 plugin.

**Comment by mstahv** [comment]
The service only supports Vaadin releases in maven central. If you need to use SNAPSHOT release, I'm afraid you'll have to fall back to traditional widgetset compilation.

**Comment by gokhanoner** [comment]
OK, thank :) I think I can wait for a couple of weeks :)
