### ISSUE TITLE
wscdn.vaadin.com doesn't work for ckeditor-wrapper-for-vaadin, but cdn.virit.in works

### ISSUE THREAD

**Issue by shabak** [viritin/vwscdn#8]
When I followed all the instructions at https://wscdn.vaadin.com/, I got the error:
![image](https://cloud.githubusercontent.com/assets/8171173/15504606/759562a2-21c8-11e6-83b2-5bcdbd46c333.png)

But in case of using http://cdn.virit.in/ it works well!

There is the repository shows the issue: https://github.com/shabak/vaadin-cdn-issue

**Comment by mstahv** [comment]
I nailed this, the service was giving some wrong mime headers. But with old versions it is probably still broken for a while as the CDN proxy has cached the invalid headers.

Thanks for pointing this out!
